### PR TITLE
Allow custom lock options, and custom filemodes.

### PR DESCRIPTION
**Pull request by jaketothepast**
Implements #9 and #15 . Essentially, adds 2 new keys to look for in options, `lock_options` and `modes` which can both be used when calling Filelock.

Changes the actual algorithm of the Filelock function to not wait if `File::LOCK_NB` was present in the logical or of the lock options.

This is @jake-windle's personal account.

### CODE REVIEW

**Comment by sheerun** [comment]
Could you fix travis build errors?

**Comment by jaketothepast** [comment]
Yep! Gotta figure out why it broke, I've only ever used Ruby 2

**Comment by jaketothepast** [comment]
Alright, I've got it, pushing the fix now

**Comment by sheerun** [comment]
Almost there :) Please add set ruby versions to following:

```
  - "1.8"
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - jruby-19mode
  - jruby-18mode
```

+ any version of rubinius that works

**Comment by sheerun** [comment]
btw. in the future it's good to mark "allow edits" checkbox when sending PR :)

**Pull request closed without merging**
