### PR TITLE
Add lock wait feature and custom exceptions

### PR DESCRIPTION
**Pull request by jasonwbarnett**
I needed the option for a lock wait timeout, similar to flock. I also thought there should be some custom exceptions for Filelock with decent descriptions so when using the library within your app, it's obvious what's causing the issue.

### CODE REVIEW

**Comment by sparrovv** [comment]
I like that change. It's something I was just thinking about, as I have a use-case where I'd like to skip if the lock is taken. 

@sheerun does it require anything else to be merged?

**Comment by jasonwbarnett** [comment]
@sparrovv It's been a long time since I looked at this (1 year)... but I am fairly confident this worked really well and is all good.

**Comment by sparrovv** [comment]
@jasonwbarnett yes, I've run a few tests on ruby 2.0.0 and it works as expected. Good job :+1:

**Comment by sheerun** [comment]
I missed this PR.. We can't break backward compatibility so `Filelock::WaitTimeout` and `Filelock::ExecTimeout` should inherit from `Timeout::Error`.

Please add new tests instead of modyfying existing ones, and I'll merge and release right away :)

**Comment by jasonwbarnett** [comment]
great suggestions, that makes a lot of sense. I'll push the updates tomorrow.

**Comment by jasonwbarnett** [comment]
finally got this working.... had to fight with Travis CI and bundler.

**Comment by sheerun** [comment]
Great, thank you :)

**Comment by sheerun** [comment]
I've released it as 1.1.0, but I've changed default `:wait` value to 1 day, so behavior is more or less backward compatible :) Thank you for contributing!

**Pull request merged**
